# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GradParamLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, epsOR)
}

GradParamLogLikPersTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLikPersTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

GradParamLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

GradParamLogLikWithInter <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLikWithInter', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR)
}

GradPenalLogLik <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLik', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikNullModelOR <- function(param, YNT, riskNT, riskT, YT, XNT, XT, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikNullModelOR', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPers <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPers', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPersNullModelOR <- function(param, YNT, riskNT, riskT, YT, XNT, XT, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPersNullModelOR', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPersTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPersTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPersWithInter <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPersWithInter', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikWithInter <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikWithInter', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

OddsRatioTime <- function(YNT, YT, riskNT, riskT) {
    .Call('_LongitSemiComp_OddsRatioTime', PACKAGE = 'LongitSemiComp', YNT, YT, riskNT, riskT)
}

ParamLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_ParamLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, epsOR)
}

ParamLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_ParamLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

ParamLogLikWithInter <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR) {
    .Call('_LongitSemiComp_ParamLogLikWithInter', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR)
}

PenalLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

PenalLogLikNoX <- function(param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLikNoX', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, epsOR)
}

PenalLogLikNullModelOR <- function(param, YT, YNT, riskNT, riskT, XNT, XT, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLikNullModelOR', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, TimeBase, TimePen, lambda, epsOR)
}

PenalLogLikORconst <- function(param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikORconst', PACKAGE = 'LongitSemiComp', param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

PenalLogLikORconstNoX <- function(param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikORconstNoX', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

PenalLogLikORparam <- function(param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, PieceWiseTimes) {
    .Call('_LongitSemiComp_PenalLogLikORparam', PACKAGE = 'LongitSemiComp', param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, PieceWiseTimes)
}

PenalLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

PenalLogLikWithInter <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLikWithInter', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

