# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
FirstOne <- function(x) {
    .Call('_LongitSemiComp_FirstOne', PACKAGE = 'LongitSemiComp', x)
}

#' @export
GradPenalLogLik <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLik', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

#' @export
GradPenalLogLikPers <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPers', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

#' @export
OddsRatioTime <- function(YNT, YT, riskNT, riskT) {
    .Call('_LongitSemiComp_OddsRatioTime', PACKAGE = 'LongitSemiComp', YNT, YT, riskNT, riskT)
}

#' @export
ParamLogLik <- function(param, X, YNT, YT, riskNT, riskT) {
    .Call('_LongitSemiComp_ParamLogLik', PACKAGE = 'LongitSemiComp', param, X, YNT, YT, riskNT, riskT)
}

#' @export
PenalLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

#' @export
PenalLogLikNoX <- function(param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikNoX', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

#' @export
PenalLogLikORconst <- function(param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikORconst', PACKAGE = 'LongitSemiComp', param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

#' @export
PenalLogLikORconstNOBetaOR <- function(param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikORconstNOBetaOR', PACKAGE = 'LongitSemiComp', param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

#' @export
PenalLogLikORconstNoX <- function(param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda) {
    .Call('_LongitSemiComp_PenalLogLikORconstNoX', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda)
}

#' @export
PenalLogLikORparam <- function(param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, PieceWiseTimes) {
    .Call('_LongitSemiComp_PenalLogLikORparam', PACKAGE = 'LongitSemiComp', param, X, YNT, riskNT, riskT, YT, TimeBase, TimePen, lambda, PieceWiseTimes)
}

